### ISSUE TITLE
Can't retrieve data from REST Service

### ISSUE THREAD

**Issue by Ekitchi** [Ekitchi/ppe-mdl-mobile#1]
L'accès aux données du serveur via le service REST utilisé ne semblent pas fonctionner en lieu d'une erreur "Cross-Domain".

**Comment by Erwhann-Rouge** [comment]
Pour le dev l'erreur peut être résolue en désactivant la vérification de l'origine de la requête DEPUIS le navigateur.
Hack Firefox : https://github.com/spenibus/cors-everywhere-firefox-addon
